"use client";

import { useState } from "react";
import GamePlayer from "./GamePlayer";

const icons={"Cookie Clicker":"🍪","Retro Bowl":"🏈","Slope":"↘","Rocket Goal":"🚀","Geometry Dash":"◆","Moto X3M":"🏍","Moto X3M 2":"🏍","Moto X3M 3":"🏍","Moto X3M 4 Winter":"❄","Moto X3M 5 Pool Party":"🌊","Moto X3M 6 Spooky Land":"☠","Eaglercraft":"▦","Level Devil":"⚠","Basketball Stars":"🏀","Happy Wheels":"●","Minesweeper":"💣","Worlde":"W","Slither.io":"🐍","Chess":"♞","Tetris":"▦","FNAF":"★","Subway Surfers":"🚆","Among Us":"●","Space Waves":"🚀","Speed Stars":"★","Stickman Hook":"⌁","SoFlo Wheelie Life":"🏍"};
function localDateKey(){const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function achievements(played,favorites,recent,days){if(localStorage.getItem("vehemence_notify_achievements")==="false")return;const u=JSON.parse(localStorage.getItem("vehemence_achievement_unlocks")||"[]"),n=JSON.parse(localStorage.getItem("vehemence_notifications")||"[]"),c=[["first-game",played>=1,"First Game","You played your first game."],["collector",favorites.length>=5,"Collector","You favorited 5 games."],["regular",days.length>=7,"Regular","You played on 7 different days."],["explorer",recent.length>=10,"Explorer","You played 10 different games."],["veteran",played>=50,"Veteran","You played 50 games."]];let changed=false;c.forEach(([id,ok,title,text])=>{if(ok&&!u.includes(id)){u.push(id);n.unshift({id:`achievement-${id}`,title:`Achievement unlocked: ${title}`,text,type:"Achievement",read:false});changed=true}});if(changed){localStorage.setItem("vehemence_achievement_unlocks",JSON.stringify(u));localStorage.setItem("vehemence_notifications",JSON.stringify(n.slice(0,100)));window.dispatchEvent(new Event("vehemence-notifications-changed"))}}
export default function GameCard({game,favorite=false,onFavorite,onOpen}){const[open,setOpen]=useState(false);function start(){if(localStorage.getItem("vehemence_remember_game")!=="false")localStorage.setItem("vehemence_last_game",game.name);const r=JSON.parse(localStorage.getItem("vehemence_recent_games")||"[]").filter(x=>x!==game.name),recent=[game.name,...r].slice(0,20);localStorage.setItem("vehemence_recent_games",JSON.stringify(recent));const played=Number(localStorage.getItem("vehemence_games_played")||0)+1;localStorage.setItem("vehemence_games_played",String(played));const today=localDateKey(),old=JSON.parse(localStorage.getItem("vehemence_active_days")||"[]").filter(x=>x!==today),days=[today,...old].slice(0,365);localStorage.setItem("vehemence_active_days",JSON.stringify(days));achievements(played,JSON.parse(localStorage.getItem("vehemence_favorites")||"[]"),recent,days);window.dispatchEvent(new Event("vehemence-games-changed"));onOpen?.(game);setOpen(true)}return<><article className="game-card"><button type="button" className="game-card-main" onClick={start}><div className="game-thumbnail"><div className="game-thumb-shine"/><span className="game-thumb-icon">{icons[game.name]||"★"}</span><span className="game-thumb-name">{game.name}</span></div><div className="game-info"><div><h3>{game.name}</h3><p>{game.description}</p></div><span className="game-category">{game.category}</span></div></button><button type="button" className={`game-favorite ${favorite?"active":""}`} aria-label={favorite?`Remove ${game.name} from favorites`:`Add ${game.name} to favorites`} onClick={()=>onFavorite?.(game.name)}>{favorite?"★":"☆"}</button></article>{open&&<GamePlayer game={game} onClose={()=>setOpen(false)}/>}</>}
